version: '3.6'
services:
  db-service:
    build:
      context: db/mysql/.
      dockerfile: Dockerfile
      args:
        DB_BASE_IMAGE: mysql
    image: geohash-mysql
    shm_size: '1gb'
    ports:
      - "4305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: geovocab
